### PR TITLE
add: card component docs

### PR DESCRIPTION
**Pull request by nayyyhaa**
- Added documentation for card component.
- Refactor grid layout.

### CODE REVIEW

**Review by mikesch803 — APPROVED** [review]
LGTM

**Comment by Dev-AkshatGupta** [comment]
Neha UI looks dope and coding is all up to date

**Review by Dev-AkshatGupta — APPROVED** [review]
LGTM

**Review by vrx29 — APPROVED** [review]
Nice UI. Looks good to me.

**Comment by nayyyhaa** [comment]
Thanks @mikesch803 , @Dev-AkshatGupta  & @vrx29 for reviewing! Merging the changes. :D

**Pull request merged**
