### PR TITLE
add: alert + avatar docs

### PR DESCRIPTION
**Pull request by nayyyhaa**
Added documentation for alert & avatar page.

### CODE REVIEW

**Review by Hamza-777 — APPROVED** [review]
Live view looks good but would like to add that avoid using infinitely running animations.

**Comment by nayyyhaa** [comment]
> Live view looks good but would like to add that avoid using infinitely running animations.

Thanks! will try to find an alternative :)

**Review by b0llu — APPROVED** [review]
Everything looks great! The animation part on landing page look really good

**Comment by nayyyhaa** [comment]
> Everything looks great! The animation part on landing page look really good

Thanks @b0llu ! 👯

**Comment by nayyyhaa** [comment]
Merging the changes.

**Review by Developers-codz — COMMENTED** [review]
UI is awesome!! good work Neha

**Pull request merged**
