### PR TITLE
add: image + input component docs

### PR DESCRIPTION
**Pull request by nayyyhaa**
- Added image & input documentation.
- added dark mode.

### CODE REVIEW

**Review by foolhardy21 — APPROVED** [review]
looks good.

**Review by VLeads — APPROVED** [review]
Everything looks good & UI is beautiful. Keep up doing the good work !!

**Comment by keshavkumar-in** [comment]
1. UI looks good and code is also fine but the image you are using is very heavy on home page. Please try to compress it. It takes so much time to load.
2.  You have a typo in "Form with Error Validations" section.
Neha Typo Mistake

**Comment by nayyyhaa** [comment]
> 1. UI looks good and code is also fine but the image you are using is very heavy on home page. Please try to compress it. It takes so much time to load.
> 2. You have a typo in "Form with Error Validations" section.
>    Neha Typo Mistake

Yes, I was thinking to compress the image but forgot. Haha! I've made the said changes. 💯

**Comment by nayyyhaa** [comment]
Thanks @foolhardy21 , @VLeads & @keshavkumar-in for reviewing. Merging the changes. :)

**Pull request merged**
