### PR TITLE
Rating nav typography

### PR DESCRIPTION
**Pull request by nayyyhaa**
Added documentation for Rating, Navigation & Typography component.

### CODE REVIEW

**Review by anik31 — APPROVED** [review]
Nice work @nayyyhaa

**Comment by mikesch803** [comment]
LGTM

**Review by mikesch803 — APPROVED** [review]

**Review by Dev-AkshatGupta — APPROVED** [review]

**Comment by Vishnu-Aithal** [comment]
Shifted Background for Text 
image
Don't know if it was intended, else you can remove offsets.

**Review by ParthParolekar — APPROVED** [review]
Looks good! Great work :+1:

**Comment by keshavkumar-in** [comment]
Rating section is fine but the navigation page has some issue in my view.
The navbar which you have coded as Fixed is not fixed and the Sticky navbar is not working as sticky.
For sticky navbar example, place some content before the navbar and on scroll the position will be fixed to top.
This is the example of fixed navbar: https://www.accenture.com/in-en
And for sticky you can take reference from this: https://www.w3schools.com/howto/howto_js_navbar_sticky.asp

**Comment by nayyyhaa** [comment]
> Shifted Background for Text image Don't know if it was intended, else you can remove offsets.

Yes, added a little offset for stying purpose

**Comment by nayyyhaa** [comment]
> Rating section is fine but the navigation page has some issue in my view. The navbar which you have coded as Fixed is not fixed and the Sticky navbar is not working as sticky. For sticky navbar example, place some content before the navbar and on scroll the position will be fixed to top. This is the example of fixed navbar: https://www.accenture.com/in-en And for sticky you can take reference from this: https://www.w3schools.com/howto/howto_js_navbar_sticky.asp

Yes, noted the points. I've made the following changes. Thanks.

**Comment by nayyyhaa** [comment]
Thanks all for reviewing. Merging the changes. 👍

**Pull request merged**
